name: "chai-courses"

services:
  redis: 
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "Test#123"]
    volumes:
      - redis:/data
    networks:
      - net  

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - net

  server:
    build:
      context: ./backend
    ports: 
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - path: ./backend/.env
    depends_on:
      - redis
      - mongo
    networks:
      - net

  client:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    env_file:
      - path: ./frontend/.env
    depends_on:
      - server
    networks:
      - net

volumes:
  redis:
  mongo:

networks:
  net:
    driver: bridge
    